# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 256694178a71164e3b9ab22aa106fbb030565d21bce33673caa3d8b0edd2ee3991b49c416abab3d7f067b88abbc0cb8baabdf7fea2f6af773b9085443e0417a4

test:
  secret_key_base: 82897b3ce86a780ef67f5534efa881d3f8a1c0f17419855a8be2a2b103acea6bfdf1bb71d1d7a1fad43b5e629f57e261da5b8f28d30301efa5828ae3e45e5eee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
